using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI
{
    [GenerateTypedNameReferences]
    sealed partial class ShipDetailsPopup : FancyWindow
    {
        private readonly VesselRow _parent;
        private VesselRow.VesselDetails _details;

        public ShipDetailsPopup(VesselRow owner)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Title = owner.Vessel?.Name ?? Loc.GetString("bound-to-grid-unknown-station");
            _parent = owner;
            GuidebookButton.Disabled = _parent.Vessel?.GuidebookPage == null;
            GuidebookButton.OnPressed += OnOpenGuidebook;
            GuidebookButton.ToolTip = _parent.Vessel?.Description;
            GuidebookButton.TooltipDelay = .2f;
            NavMapScreen.MaintainRelativeTextboxSize = false;
            OnClose += UnloadMap;
        }

        public void LoadAndShowDetails()
        {
            if (this.IsOpen) { return; }
            _details = _parent.LoadVesselDetails();
            NavMapScreen.MapUid = _details.map;

            NavMapScreen.ForceNavMapUpdate();
            OpenCentered();
        }

        private void OnOpenGuidebook(ButtonEventArgs args)
        {
            if (_parent.Vessel?.GuidebookPage == null)
                return;

            _parent.LoadVesselGuidebook();

        }

        private void UnloadMap()
        {
            _parent.DeleteGridData(_details.map);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _parent.DeleteGridData(_details.map);
            }
        }
    }
}
