using Content.Client.Guidebook;
using Content.Client.Pinpointer;
using Content.Client.Shuttles.Systems;
using Content.Client.Station;
using Content.Server.Maps;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared.Atmos;
using Content.Shared.Guidebook;
using Content.Shared.Lathe;
using Content.Shared.Pinpointer;
using Content.Shared.Shuttles.Events;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.EntitySerialization.Systems;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using static Content.Shared.Pinpointer.SharedNavMapSystem;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class VesselRow : PanelContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly EntityManager _entityManager = default!;
    private readonly ShuttleSystem _shuttleSystem = default!;
    private readonly GuidebookSystem _guidebook = default!;
    public VesselPrototype? Vessel;
    private ShipDetailsPopup _detailWindow;

    public VesselRow(VesselPrototype prototype)
    {
        Vessel = prototype;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttleSystem = _entityManager.System<ShuttleSystem>();
        _guidebook = _entitySystemManager.GetEntitySystem<GuidebookSystem>();
        _detailWindow = new(this);

        Guidebook.OnPressed += LoadVesselDetails;
    }

    public struct VesselDetails
    {
        public bool Valid = false;
        public EntityUid map;

        public VesselDetails() { }
    }

    public enum ShipyardUiKey
    {
        Key
    }

    public void RequestVesselDetails()
    {
        var details = new VesselDetails();

        try
        {
            if (Vessel?.ShuttlePath == null)
                return;

            _shuttleSystem.ShuttleDataRecieved += OnVesselData;
            _shuttleSystem.RequestShuttleData(Vessel.ShuttlePath);
        }
        catch (Exception e)
        {
            return;
        }
    }

    private void OnVesselData(ShuttleDataResponse response)
    {
        if (response.Map != null && response.ShuttleResPath == Vessel?.ShuttlePath)
        {
            _shuttleSystem.ShuttleDataRecieved -= OnVesselData;
            if (response.Map.HasValue)
            {
                _detailWindow.ShowDetails(new VesselDetails() { Valid = true, map = _entityManager.GetEntity(response.Map.Value) });
            } else
            {
                LoadVesselGuidebook();
            }
        }
    }

    private void LoadVesselDetails(BaseButton.ButtonEventArgs args)
    {
        _detailWindow.RequestDetails();
    }

    public void LoadVesselGuidebook()
    {
        if (Vessel?.GuidebookPage == null)
            return;

        List<ProtoId<GuideEntryPrototype>> guidebookEntries = new() { Vessel.GuidebookPage.Value };
        _guidebook.OpenHelp(guidebookEntries);

    }
}
